name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Server via SFTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: sftp.woocommander.ai 
        username: woocommander.ai
        password: ${{ secrets.PASSWORD }}
        port: 22
        server-dir: /customers/0/7/b/woocommander.ai/httpd.www/